```yaml
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

# Site settings
title: "Pranab Bagartti's Homepage"
description: "Pranab Bagartti's academic website"
author: "Pranab Bagartti"

# Navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "Resources"
    url: "/resources.html"
  - title: "Publications"
    url: "/publications.html"
  - title: "CV"
    url: "/cv.html"
```